FROM ruby:2.6-alpine

# See also: https://github.com/asciidoctor/docker-asciidoctor

RUN apk add --no-cache \
  build-base \
  ca-certificates \
  curl \
  findutils \
  font-bakoma-ttf \
  graphviz \
  inotify-tools \
  libxml2-dev \
  make \
  openjdk8-jre \
  py3-pillow \
  python3 \
  python3-dev \
  ruby \
  ruby-dev \
  ruby-mathematical \
  ruby-rake \
  ttf-dejavu \
  ttf-liberation \
  tzdata  

WORKDIR /website